# Generated by Django 5.1.1 on 2024-09-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="state",
        ),
    ]
