# Generated by Django 5.1.1 on 2024-09-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(default="Gujarat", max_length=20),
            preserve_default=False,
        ),
    ]
