# Generated by Django 5.1.5 on 2025-04-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_businesscategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
